# Generated by Django 5.1.15 on 2026-02-25 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('metric_type', models.CharField(choices=[('precision_at_10', 'Precision@10'), ('precision_at_win', 'Precision@Win'), ('recall_at_10', 'Recall@10')], max_length=50)),
                ('recommended_count', models.IntegerField(default=0)),
                ('pursued_count', models.IntegerField(default=0)),
                ('won_count', models.IntegerField(default=0)),
                ('precision_score', models.FloatField(default=0.0)),
                ('recommended_ids', models.JSONField(default=list)),
                ('pursued_ids', models.JSONField(default=list)),
                ('won_ids', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'metric_type')},
            },
        ),
        migrations.CreateModel(
            name='RevenueForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast_date', models.DateField()),
                ('quarter', models.CharField(max_length=10)),
                ('pipeline_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('weighted_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expected_wins', models.IntegerField(default=0)),
                ('confidence_low', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('confidence_high', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deal_details', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-forecast_date', 'quarter'],
                'unique_together': {('forecast_date', 'quarter')},
            },
        ),
    ]
