# Generated by Django 5.1.15 on 2026-02-26 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_recommendationmetric_revenueforecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(db_index=True, max_length=255)),
                ('deal_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('action', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('hallucination_flags', models.IntegerField(default=0)),
                ('citations_present', models.BooleanField(blank=True, null=True)),
                ('human_edit_delta', models.FloatField(blank=True, help_text='Fraction (0–1) of agent output that was changed by a human reviewer.', null=True)),
                ('override', models.BooleanField(default=False, help_text="True if a human rejected or overrode the agent's output.")),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('autonomy_level', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent Run',
                'verbose_name_plural': 'AI Agent Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality_score', models.IntegerField(help_text='Overall output quality, 1 (very poor) to 5 (excellent).')),
                ('accuracy_score', models.IntegerField(blank=True, help_text='Factual accuracy of the output, 1–5.', null=True)),
                ('usefulness_score', models.IntegerField(blank=True, help_text='Practical usefulness of the output, 1–5.', null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_evaluations', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='analytics.aiagentrun')),
            ],
            options={
                'verbose_name': 'AI Evaluation',
                'verbose_name_plural': 'AI Evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAgentMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(blank=True, default='', max_length=100)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.aiagentrun')),
            ],
            options={
                'verbose_name': 'AI Agent Metric',
                'verbose_name_plural': 'AI Agent Metrics',
                'unique_together': {('run', 'metric_name')},
            },
        ),
    ]
