# Generated by Django 5.1.15 on 2026-02-25 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_technicalsolution_architecturediagram_solutionvalidationreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedTeamFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('fully_addressed', 'Fully Addressed'), ('partially_addressed', 'Partially Addressed'), ('not_addressed', 'Not Addressed')], max_length=25)),
                ('gap_description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('recommendation', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_team_findings', to='proposals.proposal')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_team_findings', to='proposals.proposalsection')),
            ],
            options={
                'ordering': ['-severity', 'requirement_id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('content', 'Content'), ('formatting', 'Formatting'), ('compliance', 'Compliance'), ('administrative', 'Administrative')], default='content', max_length=20)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_checklist', to='proposals.proposal')),
            ],
            options={
                'ordering': ['category', 'item_name'],
            },
        ),
    ]
