# Generated by Django 5.1.15 on 2026-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='competitorprofile',
            new_name='research_co_cage_co_af0905_idx',
            old_name='research_competitorprofile_cage_code_idx',
        ),
        migrations.RenameIndex(
            model_name='competitorprofile',
            new_name='research_co_is_acti_026c59_idx',
            old_name='research_competitorprofile_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='marketintelligence',
            new_name='research_ma_categor_36dfd6_idx',
            old_name='research_marketintelligence_category_idx',
        ),
        migrations.RenameIndex(
            model_name='marketintelligence',
            new_name='research_ma_publish_03f794_idx',
            old_name='research_marketintelligence_published_date_idx',
        ),
        migrations.RenameIndex(
            model_name='researchproject',
            new_name='research_re_deal_id_a2a730_idx',
            old_name='research_researchproject_deal_research_type_idx',
        ),
        migrations.RenameIndex(
            model_name='researchproject',
            new_name='research_re_status_b7f7d0_idx',
            old_name='research_researchproject_status_idx',
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='List of {url, title, relevance_score, snippet}'),
        ),
    ]
