# Generated by Django 5.1.15 on 2026-02-25 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_agencycontact_agencyinteraction_captureplan_and_more'),
        ('pricing', '0001_initial'),
        ('proposals', '0004_redteamfinding_submissionchecklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingVolume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('final', 'Final')], default='draft', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('odc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('price_defense_document', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pricing_volumes', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_volumes', to='deals.deal')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_volumes', to='proposals.proposal')),
                ('selected_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_volumes', to='pricing.pricingscenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
