# Generated by Django 5.1.15 on 2026-03-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricingvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingscenario',
            name='cost_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.costmodel'),
        ),
        migrations.AlterField(
            model_name='pricingscenario',
            name='margin_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pricingscenario',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pricingscenario',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
