# Generated by Django 5.1.15 on 2026-02-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at_notification',
        ),
    ]
