# Generated by Django 5.1.15 on 2026-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='businesspolicy',
            new_name='policies_bu_is_acti_f81a7f_idx',
            old_name='policies_bp_active_type_idx',
        ),
        migrations.RenameIndex(
            model_name='businesspolicy',
            new_name='policies_bu_scope_df9a8e_idx',
            old_name='policies_bp_scope_active_idx',
        ),
        migrations.RenameIndex(
            model_name='policyevaluation',
            new_name='policies_po_deal_id_a34de3_idx',
            old_name='policies_pe_deal_outcome_idx',
        ),
        migrations.RenameIndex(
            model_name='policyevaluation',
            new_name='policies_po_policy__9baf86_idx',
            old_name='policies_pe_policy_evat_idx',
        ),
        migrations.RenameIndex(
            model_name='policyevaluation',
            new_name='policies_po_deal_id_32c382_idx',
            old_name='policies_pe_deal_pol_evat_idx',
        ),
        migrations.RenameIndex(
            model_name='policyexception',
            new_name='policies_po_status_0c8330_idx',
            old_name='policies_pex_status_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='policyexception',
            new_name='policies_po_deal_id_35be9b_idx',
            old_name='policies_pex_deal_pol_sts_idx',
        ),
        migrations.AlterField(
            model_name='businesspolicy',
            name='actions',
            field=models.JSONField(default=dict, help_text="Actions to take when policy is triggered, e.g. {'notify': ['manager'], 'block_submission': true}"),
        ),
        migrations.AlterField(
            model_name='businesspolicy',
            name='conditions',
            field=models.JSONField(default=dict, help_text="Conditions that must be met for this policy to apply, e.g. {'deal_type': 'IDIQ', 'min_value': 100000}"),
        ),
        migrations.AlterField(
            model_name='businesspolicy',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower number = higher priority. Policies are evaluated in ascending priority order.'),
        ),
        migrations.AlterField(
            model_name='policyevaluation',
            name='auto_resolved',
            field=models.BooleanField(default=False, help_text='True if the evaluation outcome was resolved automatically without human intervention.'),
        ),
        migrations.AlterField(
            model_name='policyevaluation',
            name='recommendations',
            field=models.JSONField(default=list, help_text='List of recommended actions to resolve warnings or failures.'),
        ),
        migrations.AlterField(
            model_name='policyevaluation',
            name='triggered_rules',
            field=models.JSONField(default=list, help_text="List of rule evaluation details that contributed to the outcome, e.g. [{'rule_id': '...', 'rule_name': '...', 'passed': false, 'message': '...'}]"),
        ),
        migrations.AlterField(
            model_name='policyexception',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, the exception automatically becomes inactive after this datetime.', null=True),
        ),
        migrations.AlterField(
            model_name='policyexception',
            name='reason',
            field=models.TextField(help_text='Justification provided by the requester for the exception.'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Message shown to the user when this rule produces a blocking failure.'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='field_path',
            field=models.CharField(help_text="Dot-notation path to the field on the deal object, e.g. 'contract_value' or 'metadata.risk_score'", max_length=255),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='is_blocking',
            field=models.BooleanField(default=True, help_text="If True, a rule violation will produce a 'fail' outcome. If False, it will produce a 'warn' outcome."),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='threshold_json',
            field=models.JSONField(blank=True, help_text='Structured threshold for list-based operators (in, not_in, contains).', null=True),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='threshold_value',
            field=models.CharField(blank=True, default='', help_text='Scalar threshold for simple comparisons (gt, lt, eq, gte, lte).', max_length=255),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='warning_message',
            field=models.TextField(blank=True, default='', help_text='Message shown to the user when this rule produces a non-blocking warning.'),
        ),
    ]
