# Generated by Django 5.1.15 on 2026-02-26 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_rename_policies_bp_active_type_idx_policies_bu_is_acti_f81a7f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutonomyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('policy_json', models.JSONField(default=dict, help_text='Full policy document, e.g. {current_autonomy_level, kill_switch_active, hitl_risk_threshold, autonomy_levels: {0: {allowed_actions: [...]}, ...}}')),
                ('autonomy_level', models.IntegerField(choices=[(0, 'L0 — Assist only'), (1, 'L1 — Guided automation'), (2, 'L2 — Conditional autonomy'), (3, 'L3 — Strategic autonomy')], default=1, help_text='Top-level autonomy level for quick reference (mirrors policy_json).')),
                ('kill_switch_active', models.BooleanField(default=False, help_text='If True, all AI actions require HITL regardless of level or risk score.')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('scope_json', models.JSONField(default=dict, help_text="Scope constraints, e.g. {'agency_allowlist': ['DoD'], 'max_deal_value': 5000000}")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_autonomy_policies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_autonomy_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Autonomy Policy',
                'verbose_name_plural': 'AI Autonomy Policies',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='AIIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('incident_type', models.CharField(choices=[('hallucination', 'Hallucination'), ('incorrect_submission', 'Incorrect Submission'), ('clause_missed', 'Clause Missed'), ('data_breach', 'Data Breach'), ('pricing_error', 'Pricing Error'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=15)),
                ('deal_id', models.CharField(blank=True, default='', max_length=255)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('freeze_autonomy', models.BooleanField(default=False, help_text='If True, the kill switch was (or should be) activated in response to this incident.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_ai_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Incident',
                'verbose_name_plural': 'AI Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_approvals', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='policies.aiautonomypolicy')),
            ],
            options={
                'verbose_name': 'Policy Approval',
                'verbose_name_plural': 'Policy Approvals',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyEnforcementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_name', models.CharField(db_index=True, max_length=255)),
                ('deal_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('decision', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('hitl_required', 'HITL Required')], db_index=True, max_length=20)),
                ('autonomy_level', models.IntegerField(default=1)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enforcement_logs', to='policies.aiautonomypolicy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enforcement_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Enforcement Log',
                'verbose_name_plural': 'Policy Enforcement Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
