# Generated by Django 5.1.15 on 2026-02-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_vault', '0002_knowledgevault_knowledgechunk_solutioningframework'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='knowledge_v_vault_i_c14849_idx',
            old_name='kv_chunk_vault_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='knowledge_v_documen_231264_idx',
            old_name='kv_chunk_doc_idx',
        ),
    ]
