# Generated by Django 5.1.15 on 2026-02-25 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('agency', models.CharField(blank=True, max_length=500)),
                ('office', models.CharField(blank=True, max_length=500)),
                ('contact_type', models.CharField(choices=[('cor', 'Contracting Officer Representative'), ('co', 'Contracting Officer'), ('tpoc', 'Technical Point of Contact'), ('pm', 'Program Manager'), ('end_user', 'End User'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('relationship_strength', models.IntegerField(default=1, help_text='1-5 scale: 1=cold, 5=strong relationship')),
            ],
            options={
                'ordering': ['-relationship_strength', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('meeting', 'Meeting'), ('email', 'Email'), ('phone', 'Phone Call'), ('conference', 'Conference'), ('industry_day', 'Industry Day'), ('site_visit', 'Site Visit'), ('other', 'Other')], max_length=20)),
                ('date', models.DateTimeField()),
                ('summary', models.TextField()),
                ('attendees', models.JSONField(default=list)),
                ('follow_up_actions', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CapturePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('win_strategy', models.TextField(blank=True)),
                ('competitive_landscape', models.TextField(blank=True)),
                ('teaming_strategy', models.TextField(blank=True)),
                ('pricing_approach', models.TextField(blank=True)),
                ('technical_approach_summary', models.TextField(blank=True)),
                ('key_differentiators', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('risk_assessment', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=dict)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GateReviewCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=True)),
                ('evaluation_query', models.TextField(blank=True, help_text='Python expression or model query for auto-evaluation')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gate Review Criteria',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('organization', models.CharField(blank=True, max_length=500)),
                ('role_in_decision', models.CharField(blank=True, max_length=200)),
                ('influence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('disposition', models.CharField(choices=[('champion', 'Champion'), ('supporter', 'Supporter'), ('neutral', 'Neutral'), ('skeptic', 'Skeptic'), ('blocker', 'Blocker'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('priorities', models.JSONField(default=list)),
                ('concerns', models.JSONField(default=list)),
                ('engagement_strategy', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-influence_level', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_stage_f562ff_idx',
            old_name='deals_deal_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_owner_i_f2c1d9_idx',
            old_name='deals_deal_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_priorit_bb34d7_idx',
            old_name='deals_deal_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_due_dat_e9fed1_idx',
            old_name='deals_deal_due_date_idx',
        ),
        migrations.AddField(
            model_name='agencycontact',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_contacts', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='agencyinteraction',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='deals.agencycontact'),
        ),
        migrations.AddField(
            model_name='agencyinteraction',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_interactions', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='agencyinteraction',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='captureplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_capture_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='captureplan',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capture_plan', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='deals.deal'),
        ),
    ]
