# Generated by Django 5.1.15 on 2026-02-25 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationthread',
            name='participants',
            field=models.ManyToManyField(related_name='communication_threads', through='communications.ThreadParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
