# Generated by Django 5.1.15 on 2026-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farclause',
            name='applicability_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dollar threshold above which this clause applies.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='farclause',
            name='clause_number',
            field=models.CharField(help_text='FAR clause number, e.g. "52.204-21"', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='farclause',
            name='compliance_checklist',
            field=models.JSONField(blank=True, default=list, help_text='List of checklist items for compliance verification.'),
        ),
        migrations.AlterField(
            model_name='farclause',
            name='related_dfars',
            field=models.JSONField(blank=True, default=list, help_text='List of related DFARS clause numbers.'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequirement',
            name='applicable_contract_types',
            field=models.JSONField(blank=True, default=list, help_text='Contract types this applies to: FFP, T&M, CPFF, CPAF, IDIQ.'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequirement',
            name='applicable_set_asides',
            field=models.JSONField(blank=True, default=list, help_text='Set-aside categories this applies to.'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequirement',
            name='compliance_criteria',
            field=models.JSONField(blank=True, default=list, help_text='List of criteria that must be met for compliance.'),
        ),
    ]
