# Generated by Django 5.1.15 on 2026-02-25 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment_number', models.IntegerField(default=1)),
                ('change_type', models.CharField(choices=[('deadline_extended', 'Deadline Extended'), ('deadline_shortened', 'Deadline Shortened'), ('scope_modified', 'Scope Modified'), ('set_aside_changed', 'Set-Aside Changed'), ('evaluation_criteria_changed', 'Evaluation Criteria Changed'), ('cancelled', 'Cancelled'), ('reissued', 'Reissued'), ('qa_posted', 'Q&A Posted'), ('attachment_added', 'Attachment Added'), ('other', 'Other')], max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_material', models.BooleanField(default=True)),
                ('impact_assessment', models.TextField(blank=True)),
                ('requires_rescore', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_notice__d20713_idx',
            old_name='opportunities_o_notice__idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_agency_89fa80_idx',
            old_name='opportunities_o_agency_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_naics_c_d27987_idx',
            old_name='opportunities_o_naics_c_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_status_fb4df4_idx',
            old_name='opportunities_o_status_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_respons_a56438_idx',
            old_name='opportunities_o_respons_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_posted__5c2dfd_idx',
            old_name='opportunities_o_posted__idx',
        ),
        migrations.AddField(
            model_name='opportunityamendment',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='opportunities.opportunity'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityamendment',
            unique_together={('opportunity', 'amendment_number')},
        ),
    ]
