# Generated by Django 5.1.15 on 2026-02-25 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={},
        ),
        migrations.AlterField(
            model_name='contractmodification',
            name='impact_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Positive or negative dollar impact.', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='ContractHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.FloatField(help_text='Overall health score from 0 to 100.')),
                ('milestone_delivery_score', models.FloatField(default=0.0, help_text='Score based on milestone on-time delivery rate (0-100).')),
                ('modification_score', models.FloatField(default=0.0, help_text='Score based on modification frequency and severity (0-100).')),
                ('burn_rate_score', models.FloatField(default=0.0, help_text='Score based on budget burn rate versus plan (0-100).')),
                ('compliance_score', models.FloatField(default=0.0, help_text='Score based on compliance posture (0-100).')),
                ('last_assessed_at', models.DateTimeField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('risk_factors', models.JSONField(default=list, help_text='List of identified risk factors.')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommended actions to improve health.')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Health',
                'verbose_name_plural': 'Contract Health Records',
                'ordering': ['-last_assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('exercised', 'Exercised'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('exercised_date', models.DateField(blank=True, null=True)),
                ('decision_deadline', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_year_details', to='contracts.contract')),
            ],
            options={
                'ordering': ['year_number'],
                'unique_together': {('contract', 'year_number')},
            },
        ),
    ]
